apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "enterprisebot-service.fullname" . }}

data:
  APP_NAME: {{ .Values.config.appName | quote }}
  VERSION: {{ .Values.config.version | quote }}
