apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "enterprisebot-service.fullname" . }}
  labels:
    app: {{ include "enterprisebot-service.name" . }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ include "enterprisebot-service.name" . }}

  template:
    metadata:
      labels:
        app: {{ include "enterprisebot-service.name" . }}

    spec:
      containers:
        - name: {{ include "enterprisebot-service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          securityContext:
            runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
            allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          envFrom:
            - configMapRef:
                name: {{ include "enterprisebot-service.fullname" . }}

          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10

          resources:
{{- toYaml .Values.resources | nindent 12 }}
